---
title: "cutandrun_EpiCompare" 
author: "Xindong"
date: "Most recent update:<br> `r Sys.Date()`"
output: 
  rmarkdown::html_document: 
    theme: spacelab
    highlight: zenburn 
    code_folding: show 
    toc: true 
    toc_float: true
    smooth_scroll: true
    number_sections: false 
    self_contained: true 
editor_options: 
  chunk_output_type: inline
---
 
```{r setup, include=T, message=F} 
root.dir <- here::here()
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  root.dir = root.dir
  # fig.height = 12,
  # fig.width = 10
)  
knitr::opts_knit$set(root.dir = root.dir, dpi = 300)   
```
### Load the EpiCompare package
```{r}
library(EpiCompare)
```
### Load the cutandrun called peaks and ENCODE reference
```{r}
H3K27ac_200_control <- ChIPseeker::readPeakFile("/Users/apple/Downloads/cutandrun_EpiCompare/1st_trial/called_peaks/H3K27ac_200_dedup_control.peaks.stringent.bed", as = "GRanges")
H3K27ac_200_top001 <- ChIPseeker::readPeakFile("/Users/apple/Downloads/cutandrun_EpiCompare/1st_trial/called_peaks/H3K27ac_200_dedup_top001.peaks.stringent.bed", as = "GRanges")

H3K27ac_ENCODE <- ChIPseeker::readPeakFile("/Users/apple/Downloads/ENCFF038DDS.bed", as = "GRanges")

peaklist <- list(H3K27ac_200_control, H3K27ac_200_top001)
names(peaklist) <- c("H3K27ac_200_control", "H3K27ac_200_top001") 

ENCODE <- list("H3K27ac_ENCODE" = H3K27ac_ENCODE)

gc()
```


### Load the hg38 blacklist
```{r}
data(hg38_blacklist)
data(hg19_blacklist)
```

### Run the EpiCompare
```{r}
EpiCompare(peakfiles = peaklist,
           genome_build = "hg19",
           blacklist = hg19_blacklist,
           picard_files = list(),
           reference = ENCODE,
           upset_plot = TRUE,
           stat_plot = TRUE,
           chromHMM_plot = TRUE,
           chromHMM_annotation = "K562",
           chipseeker_plot = TRUE,
           enrichment_plot = TRUE,
           tss_plot = TRUE,
           interact = TRUE,
           save_output = TRUE,
           output_dir = "/Users/apple/Downloads/H3K27ac_200_test")


# EpiCompare(peakfiles = peaklist,
#            genome_build = list(peakfiles="hg19",
#                                reference="hg38",
#                                blacklist="hg19"),
#            # genome_build_output = "hg19",
#            blacklist = hg19_blacklist,
#            picard_files = list(),
#            reference = ENCODE,
#            upset_plot = TRUE,
#            stat_plot = TRUE,
#            chromHMM_plot = TRUE,
#            chromHMM_annotation = "K562",
#            chipseeker_plot = TRUE,
#            enrichment_plot = TRUE,
#            tss_plot = TRUE,
#            interact = TRUE,
#            save_output = TRUE,
#            output_dir = "/Users/apple/Downloads/cutandrunEpiCompare/H3K27ac_200_hg19")

```

### Session info  

<details>

```{r Session Info, attr.output='style="max-height: 200px;"'}
utils::sessionInfo()
```

</details>








